baseURL = "/"
languageCode = "en-us"
title = "Santosh Kumar Gouda"
theme="archie"
copyright = "© santosh kumar gouda"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
# googleAnalytics = ''
[params]
	mode="auto"
	useCDN=false
	subtitle = "All things Data Engineering by Data Engineer"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sgouda0412"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/Gouda21K/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/sgouda0412/"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
